### ISSUE TITLE
Additions on "what is supported"

### ISSUE THREAD

**Issue by AbdealiJK** [databricks/spark-pandas#41]
Potentially a few things to add to the what is supported excel (giving from my list of common operations in pandas)
https://docs.google.com/spreadsheets/d/1GwBvGsqZAFFAD5PPc_lffDEXith353E1Y7UV6ZAAHWA/edit

### Pandas:
 - pd.concat()
 - pd.cut / Series.cut
 - pd.get_dummies()

### Series:
 - value_counts()
 - Common functions: min / max / argmin / abs / corr / cov / cummin / cumprod / cumsum
 - all / any
 - clip
 - fillna
 - Operations: eq / isin / lt / le / gt / ge / isna / isnull

### `pd.options`:
Options should be considered at some point.
For example, I use `with pd.option_context('mode.use_inf_as_null', True):` with `data = data[[colname]].dropna()` to drop both INFs and NAs from a dataframe.
These should be documented as not implemented right now as they do change results

### Indexes:
And I had a question as I see `set_index` and `reset_index` in the excel right now.
Is the plan that this library will implement the indexing logic on top of Spark ? (As Spark DataFrames dont have indexing)
i.e. will the index be tracked in koala and it will be a normal column in sparkDF but all index functionality will work ?

**Comment by thunterdb** [comment]
@AbdealiJK thank you for your comments. I created a task for publishing documentation, which will answer some of your questions.

Regarding pd.options: this is a good point, it would be great to understand which flags are the most useful for you so that these get prioritized.

Regarding the indexes: this is explained in a bit more details in the tutorial notebook in #34 . There is a lightweight indexing logic that covers the common use cases in pandas (and you recover this index when calling .to_pandas()). One part that has been explicitly left out is auto-alignment of series based on indexes, because this operation has a big cost in Spark (shuffling).

**Comment by AbdealiJK** [comment]
Closing as i think the excel has been updated and no further questions on index
