### ISSUE TITLE
Adding a `strict` setting to force pandas compatibility at the cost of efficiency

### ISSUE THREAD

**Issue by AbdealiJK** [databricks/spark-pandas#47]
I think that there are a bunch of design considerations that will come up.

For example - when doing `pd.DataFrame.sample()` - pandas guarantees exact records for `n` and an exact fraction when using `frac`.
When implementing them, will Koala decide to:
1. Be exactly the same as pandas and inefficient
2. Be inexact (not exactly same behavior as pandas) and be efficient

Option 1 could be implemented as:
   - Need to find num-rows
   - Do an inexact sampling in spark
   - If numRows is lower than the required, do another inexact sampling on what is left over
OR:
   - Sort data randomly and get first N records
Both are inefficient and is doing more computation than what a pure-spark solution would be. But gives the exact same number of records as pandas would.

Option 2 could be implemented as:
 - For `frac` use spark's behavior of `fraction`
 - For `n` do a count and use spark's sample() with `fraction=n/df.count()`
Neither would not give the same number of rows as pandas consistently, but requires 0 passes or max 1 pass on the data.

**Comment by AbdealiJK** [comment]
Actually - I guess a question before getting into this. What is the aim of the package:
 - Trying out a more pandas-like API for spark which could potentially be merged into pyspark later ?
 - Making it possible for current pandas developers to switch to spark with complete abstraction ?
or both to some level ?

**Comment by thunterdb** [comment]
`sample` is one of the more complex functions because of the overlap between the two functions and the difference in semantics. I am going to make a separate ticket just on this method.

To answer your last question, the goal of this package is to bring a Pandas-like experience to Spark, with the possibility of incorporating that into Spark in the future.
 - existing code in Spark must not change
 - existing code in Pandas may require some small changes, but must still be 100% compatible with Pandas after the changes. For example, this includes switching for `.ix` to `.loc`/`.iloc`, having to pass arguments by names, etc. We are still exploring the tradeoff that are required in that regard, so any feedback or code example is welcome!

**Comment by AbdealiJK** [comment]
I think the resolution of https://github.com/databricks/spark-pandas/issues/45 and https://github.com/databricks/spark-pandas/issues/49
together make this obsolete.
Will bring up any other cases I see in a case by case basis - just like the sample() case.
